### ISSUE TITLE
Rubygame broken on Mountain Lion (OS X 10.8)

### ISSUE THREAD

**Issue by sigvei** [rubygame/rubygame#21]
On Mountain Lion, rubygame 2.6.4 breaks on load with the following error message:

```
/gems/ffi-1.2.0/lib/ffi/library.rb:365:in `callback': callbacks cannot have variadic parameters (ArgumentError)
```

The relevant part of the callstack is this:

```
/gems/ruby-sdl-ffi-0.4/lib/ruby-sdl-ffi/sdl/mac.rb:161:in `<module:ObjC>'
/gems/ruby-sdl-ffi-0.4/lib/ruby-sdl-ffi/sdl/mac.rb:153:in `<module:Mac>'
/gems/ruby-sdl-ffi-0.4/lib/ruby-sdl-ffi/sdl/mac.rb:49:in `<top (required)>'
```

Line 161 is this:
    callback :imp, [:id, :sel, :varargs], :id:

Now, :varargs surely looks a lot like variadic parameters, but I am not sure what is going on.

**Comment by kranzky** [comment]
I'm getting this too.

**Comment by catwell** [comment]
See https://github.com/xrs1133/ruby-sdl-ffi/commit/0b721ac4659b4c08cda5aa2f418561a8a311e85b - I don't know why but it appears to work.

**Comment by bellmyer** [comment]
+1 for @catwell's answer. It worked for me using ruby 2.0.0-p353 and Rubygame version 2.6.4.

**Comment by marianodominguez** [comment]
Is there a way to apply this patch from gemfile ?

tried building form source (then I can use my fork)

gem 'rubygame', '2.6.4', :github => 'rubygame/rubygame'

but it does not install anything
