### ISSUE TITLE
Segmentation fault on HelloWorld rubyGame app after clean install on Windows 7

### ISSUE THREAD

**Issue by trueanalysiseu** [rubygame/rubygame#22]
G:\Projects\Sources\ruby>ruby hworld.rb
G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/nice-ffi-0.4/lib/nice-ffi/libra
ry.rb:143: [BUG] Segmentation fault
ruby 2.0.0p0 (2013-02-24) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0014 p:---- s:0063 e:000062 CFUNC  :__Linked_Version
c:0013 p:0022 s:0060 e:000058 LAMBDA G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0
/gems/nice-ffi-0.4/lib/nice-ffi/library.rb:143 [FINISH]
c:0012 p:0019 s:0055 e:000051 CLASS  G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0
/gems/rubygame-2.6.4/lib/rubygame/main.rb:29
c:0011 p:0017 s:0050 e:000049 TOP    G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0
/gems/rubygame-2.6.4/lib/rubygame/main.rb:25 [FINISH]
c:0010 p:---- s:0048 e:000047 CFUNC  :require
c:0009 p:0073 s:0044 e:000043 METHOD G:/Projects/Ruby200-x64/lib/ruby/2.0.0/ruby
gems/core_ext/kernel_require.rb:45
c:0008 p:0022 s:0034 e:000033 BLOCK  G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0
/gems/rubygame-2.6.4/lib/rubygame.rb:44 [FINISH]
c:0007 p:---- s:0031 e:000030 CFUNC  :each
c:0006 p:0060 s:0028 e:000027 TOP    G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0
/gems/rubygame-2.6.4/lib/rubygame.rb:43 [FINISH]
c:0005 p:---- s:0024 e:000023 CFUNC  :require
c:0004 p:0059 s:0020 e:000019 BLOCK  G:/Projects/Ruby200-x64/lib/ruby/2.0.0/ruby
gems/core_ext/kernel_require.rb:110
c:0003 p:0286 s:0017 e:000016 METHOD G:/Projects/Ruby200-x64/lib/ruby/2.0.0/ruby
gems/core_ext/kernel_require.rb:35
c:0002 p:0007 s:0007 E:000db0 EVAL   hworld.rb:3 [FINISH]
c:0001 p:0000 s:0002 E:001ac8 TOP    [FINISH]

hworld.rb:3:in `<main>'
G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in
`require'
G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:i
n `rescue in require'
G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:i
n`require'
G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubygame-2.6.4/lib/rubygame.rb:
43:in `<top (required)>'
G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubygame-2.6.4/lib/rubygame.rb:
43:in`each'
G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubygame-2.6.4/lib/rubygame.rb:
44:in `block in <top (required)>'
G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in
`require'
G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in
 `require'
G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubygame-2.6.4/lib/rubygame/mai
n.rb:25:in`<top (required)>'
G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rubygame-2.6.4/lib/rubygame/mai
n.rb:29:in `<module:Rubygame>'
G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/nice-ffi-0.4/lib/nice-ffi/libra
ry.rb:143:in`block (2 levels) in attach_function'
G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/nice-ffi-0.4/lib/nice-ffi/libra
ry.rb:143:in `__Linked_Version'

-- C level backtrace information -------------------------------------------
C:\Windows\SYSTEM32\ntdll.dll(NtWaitForSingleObject+0xa) [0x000000007733135A]
C:\Windows\system32\KERNELBASE.dll(WaitForSingleObjectEx+0x9c) [0x000007FEFD5510
DC]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_bugreport+0x9d) [0x0000
00006F280C8D]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_name_err_mesg_new+0x838) [
0x000000006F141418]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_bug+0x45) [0x000000006F142
1C5]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_check_safe_str+0x188) [0x0
00000006F2074E8]
 [0x0000000000401A85]
C:\Windows\SYSTEM32\ntdll.dll(_C_specific_handler+0x9c) [0x00000000772F85A8]
C:\Windows\SYSTEM32\ntdll.dll(RtlDecodePointer+0xbd) [0x0000000077309D0D]
C:\Windows\SYSTEM32\ntdll.dll(RtlUnwindEx+0xbbf) [0x00000000772F91AF]
C:\Windows\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x000000007733127
8]
G:\Projects\Ruby200-x64\lib\ruby\gems\2.0.0\gems\ffi-1.6.0\lib\ffi_c.so(Init_ffi
_c+0x3099) [0x00000000657CE6C9]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x0000
00006F26C525]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_funcall2+0x4c2) [0x0000000
06F27BA22]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_funcall2+0x8db) [0x0000000
06F27BE3B]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_funcall2+0x52a) [0x0000000
06F27BA8A]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1a9c)
 [0x000000006F2705AC]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5c89)
 [0x000000006F274799]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_eval_string+0x2fe) [0x0000
00006F2756DE]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_funcall2+0x1ba) [0x0000000
06F27B71A]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_funcall2+0x470) [0x0000000
06F27B9D0]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1b01)
 [0x000000006F270611]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5c89)
 [0x000000006F274799]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_iseq_eval+0x193) [0x000000
006F27DC13]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_rubylevel_errinfo+0x5e3) [
0x000000006F14ADA3]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_require_safe+0x44e) [0x000
000006F14C8CE]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x0000
00006F26C525]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_funcall2+0x4c2) [0x0000000
06F27BA22]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1b01)
 [0x000000006F270611]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5c89)
 [0x000000006F274799]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_yield+0x15c) [0x000000006F
27D89C]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_ary_each+0x51) [0x00000000
6F106851]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x0000
00006F26C525]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_funcall2+0x4c2) [0x0000000
06F27BA22]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1a9c)
 [0x000000006F2705AC]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5c89)
 [0x000000006F274799]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_iseq_eval+0x193) [0x000000
006F27DC13]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_rubylevel_errinfo+0x5e3) [
0x000000006F14ADA3]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_require_safe+0x44e) [0x000
000006F14C8CE]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x0000
00006F26C525]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_funcall2+0x4c2) [0x0000000
06F27BA22]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1b01)
 [0x000000006F270611]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5c89)
 [0x000000006F274799]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_iseq_eval_main+0x1e0) [0x0
00000006F27DE40]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_check_copyable+0x31f2) [0x
000000006F1470F2]
G:\Projects\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(ruby_run_node+0x51) [0x000000
006F1499E1]
 [0x0000000000402D14]
 [0x00000000004013D7]
 [0x00000000004014F8]
C:\Windows\system32\KERNEL32.dll(BaseThreadInitThunk+0xd) [0x00000000770D652D]

-- Other runtime information -----------------------------------------------
- Loaded script: hworld.rb
- Loaded features:
  
  0 enumerator.so
  1 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/x64-mingw32/enc/encdb.so
  2 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/x64-mingw32/enc/iso_8859_2.so
  3 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/x64-mingw32/enc/trans/transdb.so
  4 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/x64-mingw32/rbconfig.rb
  5 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/compatibility.rb
  6 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/defaults.rb
  7 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/deprecate.rb
  8 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/errors.rb
  9 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/version.rb
  10 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/requirement.rb
  11 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/platform.rb
  12 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/specification.rb
  13 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/exceptions.rb
  14 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/defaults/operating_system.
  rb
  15 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/x64-mingw32/enc/utf_16le.so
  16 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/x64-mingw32/enc/trans/utf_16_32.so
  17 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
  18 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
  
  19 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems.rb
  20 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/path_support.rb
  21 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/x64-mingw32/enc/trans/single_byte.s
  o
  22 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/rubygems/dependency.rb
  23 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi_c.so
  24 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/platfor
  m.rb
  25 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/types.r
  b
  26 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/library
  .rb
  27 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/errno.r
  b
  28 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/pointer
  .rb
  29 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/memoryp
  ointer.rb
  30 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/struct_
  layout_builder.rb
  31 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/struct.
  rb
  32 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/union.r
  b
  33 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/managed
  struct.rb
  34 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/callbac
  k.rb
  35 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/io.rb
  36 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/autopoi
  nter.rb
  37 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/variadi
  c.rb
  38 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/enum.rb
  
  39 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi/ffi.rb
  40 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.6.0/lib/ffi.rb
  41 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/nice-ffi-0.4/lib/nice-ffi
  /typedpointer.rb
  42 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/nice-ffi-0.4/lib/nice-ffi
  /pathset.rb
  43 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/nice-ffi-0.4/lib/nice-ffi
  /library.rb
  44 G:/Projects/Ruby200-x64/lib/ruby/2.0.0/thread.rb
  45 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/nice-ffi-0.4/lib/nice-ffi
  /autorelease.rb
  46 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/nice-ffi-0.4/lib/nice-ffi
  /struct.rb
  47 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/nice-ffi-0.4/lib/nice-ffi
  /opaquestruct.rb
  48 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/nice-ffi-0.4/lib/nice-ffi
  .rb
  49 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/mac.rb
  50 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/core.rb
  51 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/keyboard.rb
  52 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/video.rb
  53 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/audio.rb
  54 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/cdrom.rb
  55 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/event.rb
  56 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/joystick.rb
  57 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/keysyms.rb
  58 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/mouse.rb
  59 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/mutex.rb
  60 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/rwops.rb
  61 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl/timer.rb
  62 G:/Projects/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ruby-sdl-ffi-0.4/lib/ruby
  -sdl-ffi/sdl.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

G:\Projects\Sources\ruby>

G:\Projects\Sources\ruby>gem list

**\* LOCAL GEMS ***

bigdecimal (1.2.0)
ffi (1.6.0)
io-console (0.4.2)
json (1.7.7)
minitest (4.3.2)
nice-ffi (0.4)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
ruby-sdl-ffi (0.4)
rubygame (2.6.4)
test-unit (2.0.0.0)

**Comment by vision2910** [comment]
I am not sure where to find this file- hworld.rb

Let me know from where to get this file, as want to give a try for this issue...

**Comment by sajjad122** [comment]
Even though it's called Rubygame, it has uses far beyond just entertainment software. With Rubygame, you can create scientific data visualisations, educational/training tools, interactive motion graphics, and more.

---

asad
