### ISSUE TITLE
Can't install rubygame

### ISSUE THREAD

**Issue by Sygan** [rubygame/rubygame#27]
After using 
$ sudo gem install rubygame 
on Ubuntu 14.04 i've got following error. And i have no idea what is going on. 

ERROR:  Error installing rubygame:
    ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb
```

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from extconf.rb:4:in `<main>'

Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.3 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/ffi-1.9.3/ext/ffi_c/gem_make.out

**Comment by dummey** [comment]
It's a native gem which requires ruby-dev to be installed.

Try: `sudo apt-get install ruby-dev`

**Comment by Sygan** [comment]
Thanks for fast answer :) 

I'd even forgotten that i've asked this question :) 

But maybe it'll help someone with simillar problem ;).
